[default.extend-words]
# 意図的に使用している造語・固有名詞
Androider = "Androider"

[default]
extend-ignore-words-re = [
  # 偽陽性検知を減らすために3文字以下を無視する。
  # https://github.com/pankona/pankona.github.io/pull/404#issuecomment-3833238163
  # 公式ドキュメントでも4文字以下を無効化する例が挙げられているし、ここは柔軟に延ばして良い
  # https://github.com/crate-ci/typos/issues/1079 が実装された際は更新すること
  "^[a-zA-Z]{1,3}$",
]
